version: '3.4'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6379"
    restart: on-failure

  db:
    container_name: sqlite3_db
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
    restart: on-failure

  app:
    container_name: forecast
    build: .
    command: python /usr/src/forecast/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0/
    depends_on:
      - db
      - redis
    restart: on-failure

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A weatherForecast.celery worker -l info
    depends_on:
      - db
      - redis
      - app
    restart: on-failure

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A weatherForecast.celery beat -l info
    depends_on:
      - db
      - redis
      - app
    restart: on-failure
